### ISSUE TITLE
Invalidation time for Quotes

### ISSUE THREAD

**Issue by OmitNomis** [uzura89/my-daily-routine#3]
This is just a suggestion. 
This could also be a customizable option with something like.

`quoteInvalidationPeroid: "always" | "daily" | "weekly" | number (for custom)`

the period for pre-defined options will set the time accordingly, for eg: daily would have 1000 * 60 * 60 * 24. 

or a number value in milliseconds for a custom value.

**Comment by uzura89** [comment]
So this is like changing the quote in certain intervals rather than changing it on every page load, right? If so, I totally agree. However, I think "daily" is just enough for most people, so we can start from defaulting it as "daily". We could make it optional if we get any request in the future.

**Comment by OmitNomis** [comment]
Yup, that sounds good

**Comment by uzura89** [comment]
Shipped it :) I couldn't get "revalidate" option work for fetch API, so I added some caching logic in server side. 
[5bfb3b5](https://github.com/uzura89/my-daily-routine/commit/5bfb3b561cac2eec85fac7dccfbc76563e9590a2)
